### ISSUE TITLE
wrrarms doesn't work on windows 10

### ISSUE THREAD

**Issue by danilbraun** [Own-Data-Privateer/pwebarc#1]
1. `wrrarms` apparently requires `html5lib` module, but for some reason `pip` didn't install it automatically: 
```
C:\Users\user>pip install pwebarc-wrrarms
Collecting pwebarc-wrrarms
  Downloading pwebarc_wrrarms-0.11.1-py3-none-any.whl.metadata (95 kB)
     ---------------------------------------- 95.5/95.5 kB 86.7 kB/s eta 0:00:00
Collecting kisstdlib (from pwebarc-wrrarms)
  Downloading kisstdlib-0.0.3-py3-none-any.whl.metadata (568 bytes)
Collecting cbor2 (from pwebarc-wrrarms)
  Downloading cbor2-5.6.3-cp312-cp312-win_amd64.whl.metadata (6.2 kB)
Requirement already satisfied: idna in c:\python3\lib\site-packages (from pwebarc-wrrarms) (3.7)
Downloading pwebarc_wrrarms-0.11.1-py3-none-any.whl (74 kB)
   ---------------------------------------- 74.3/74.3 kB 195.3 kB/s eta 0:00:00
Downloading cbor2-5.6.3-cp312-cp312-win_amd64.whl (66 kB)
   ---------------------------------------- 66.5/66.5 kB 83.8 kB/s eta 0:00:00
Downloading kisstdlib-0.0.3-py3-none-any.whl (19 kB)
Installing collected packages: kisstdlib, cbor2, pwebarc-wrrarms
Successfully installed cbor2-5.6.3 kisstdlib-0.0.3 pwebarc-wrrarms-0.11.1

C:\Users\user>wrrarms --help
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Python3\Scripts\wrrarms.exe\__main__.py", line 4, in <module>
  File "C:\Python3\Lib\site-packages\wrrarms\__main__.py", line 41, in <module>
    from .wrr import *
  File "C:\Python3\Lib\site-packages\wrrarms\wrr.py", line 39, in <module>
    from .html import *
  File "C:\Python3\Lib\site-packages\wrrarms\html.py", line 27, in <module>
    import html5lib as _h5
ModuleNotFoundError: No module named 'html5lib'
```

2. After manually installing the `html5lib` module, another problem arose: the `fcntl` module was not found, and, apparently, it cannot be installed on Windows:

```
C:\Users\user>wrrarms --help
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Python3\Scripts\wrrarms.exe\__main__.py", line 4, in <module>
  File "C:\Python3\Lib\site-packages\wrrarms\__main__.py", line 43, in <module>
    from .io import *
  File "C:\Python3\Lib\site-packages\wrrarms\io.py", line 20, in <module>
    import fcntl as _fcntl
ModuleNotFoundError: No module named 'fcntl'

C:\Users\user>pip install fcntl
ERROR: Could not find a version that satisfies the requirement fcntl (from versions: none)
ERROR: No matching distribution found for fcntl
```

**Comment by oxij** [comment]
Fixed both issues on `testing` branch, please confirm.

Also:

- I expect `wrrarms run`, as it is currently implemented, will not work on Windows. Fixing that is on my TODO list.

- `wrrarms stream --format cbor` with vanilla `cbor2` module is currently broken (which is why I vendored my own version of `cbor2` as a submodule here).

Thanks for the report!

**Comment by danilbraun** [comment]
Yes, it works now (checked on Debian 12)
