### ISSUE TITLE
CLI: Crash when WRR contains hostname with dashes

### ISSUE THREAD

**Issue by philippelatulippe** [Own-Data-Privateer/pwebarc#5]
The idna module seems to be parsing non-IDN domain names as though they were punycode, for example `r2---sn-j5caxn0g4-axwe.googlevideo.com`. This fails with `IDNAError("Label has disallowed hyphens in 3rd and 4th position")`.

<details><summary>Stack trace</summary>
<pre>
Traceback (most recent call last):
  File "/Users/philippe/.local/pipx/venvs/hoardy-web/lib/python3.12/site-packages/hoardy_web/wrr.py", line 266, in parse_url
    net_hostname = _idna.encode(_idna.decode(ehostname, uts46=True), uts46=True).decode("ascii")
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/philippe/.local/pipx/venvs/hoardy-web/lib/python3.12/site-packages/idna/core.py", line 430, in decode
    s = ulabel(label)
        ^^^^^^^^^^^^^
  File "/Users/philippe/.local/pipx/venvs/hoardy-web/lib/python3.12/site-packages/idna/core.py", line 321, in ulabel
    check_label(label_bytes)
  File "/Users/philippe/.local/pipx/venvs/hoardy-web/lib/python3.12/site-packages/idna/core.py", line 252, in check_label
    check_hyphen_ok(label)
  File "/Users/philippe/.local/pipx/venvs/hoardy-web/lib/python3.12/site-packages/idna/core.py", line 148, in check_hyphen_ok
    raise IDNAError("Label has disallowed hyphens in 3rd and 4th position")
idna.core.IDNAError: Label has disallowed hyphens in 3rd and 4th position

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/philippe/.local/pipx/venvs/hoardy-web/lib/python3.12/site-packages/hoardy_web/__main__.py", line 2303, in main
    cargs.func(cargs)
  File "/Users/philippe/.local/pipx/venvs/hoardy-web/lib/python3.12/site-packages/hoardy_web/__main__.py", line 354, in cmd_stream
    map_wrr_paths(cargs, emit, cargs.paths, ordering=cargs.walk_fs, errors=cargs.errors)
  File "/Users/philippe/.local/pipx/venvs/hoardy-web/lib/python3.12/site-packages/hoardy_web/__main__.py", line 220, in map_wrr_paths
    map_wrr_paths_extra(cargs, lambda x, y, a, z: emit(x, y, z), paths, **kwargs)
  File "/Users/philippe/.local/pipx/venvs/hoardy-web/lib/python3.12/site-packages/hoardy_web/__main__.py", line 214, in map_wrr_paths_extra
    load_map_orderly(lambda x, y: wrr_load_expr(x, y, cargs.sniff), emit, exp_path, **kwargs)
  File "/Users/philippe/.local/pipx/venvs/hoardy-web/lib/python3.12/site-packages/hoardy_web/__main__.py", line 186, in load_map_orderly
    data = load_func(fobj, abs_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/philippe/.local/pipx/venvs/hoardy-web/lib/python3.12/site-packages/hoardy_web/__main__.py", line 214, in &lt;lambda&gt;
    load_map_orderly(lambda x, y: wrr_load_expr(x, y, cargs.sniff), emit, exp_path, **kwargs)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/philippe/.local/pipx/venvs/hoardy-web/lib/python3.12/site-packages/hoardy_web/wrr.py", line 1115, in wrr_load_expr
    reqres = wrr_load(fobj)
             ^^^^^^^^^^^^^^
  File "/Users/philippe/.local/pipx/venvs/hoardy-web/lib/python3.12/site-packages/hoardy_web/wrr.py", line 1096, in wrr_load
    res = wrr_load_raw(fobj)
          ^^^^^^^^^^^^^^^^^^
  File "/Users/philippe/.local/pipx/venvs/hoardy-web/lib/python3.12/site-packages/hoardy_web/wrr.py", line 1056, in wrr_load_raw
    purl = parse_url(_t_str("request.url", rq_url))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/philippe/.local/pipx/venvs/hoardy-web/lib/python3.12/site-packages/hoardy_web/wrr.py", line 271, in parse_url
    raise URLParsingError(url)
hoardy_web.wrr.URLParsingError: https://r2---sn-j5caxn0g4-axwe.googlevideo.com/videogoodput?id=[snip]&source=goodput&range=0-4999&expire=[snip]&ip=[snip]&ms=pm&mm=35&pl=48&sparams=id,source,range,expire,ip,ms,mm,pl&signature=[snip]&key=cms1&cpn=[snip]
There was 1 error!
</pre>
I have removed some information from the URL in the areas marked with `[snip]`.
</details>

**Comment by oxij** [comment]
This appears to be a bug in `idna`, yes.

But the tool should maybe have a work-around for this kind of thing anyway.
Generate a warning and use the original hostname instead of crashing, maybe.
After all, it does not control its inputs and, while this instance looks like a bug in `idna`, `WRR` files can come from other sources, not just the browser.

Anyway, thanks for reporting this! I'll think about the proper way to handle this a bit more.

**Comment by oxij** [comment]
This should be fixed with [tool-v0.15.4](https://github.com/Own-Data-Privateer/hoardy-web/releases/tag/tool-v0.15.4). Do reopen if it is not.

**Comment by oxij** [comment]
And there's also a follow-up for this in [tool-v0.15.5](https://github.com/Own-Data-Privateer/hoardy-web/releases/tag/tool-v0.15.5.1).
